image: node:9.11.2

pipelines:
  branches:
    master:
      -step:
        script:
          - yarn
          - yarn build
          - rm -rf src
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING.git master

