image: node:9.11.2

pipelines:
  branches:
    master:
      environment:
        MAILGUN_DOMAIN: $MAILGUN_DOMAIN
        MAILGUN_SECRET: $MAILGUN_SECRET
        JSON_SECRET: $JSON_SECRET
        MONGO_URL: $MONGO_URL
      -step:
        script:
          - yarn
          - yarn build
          - rm -rf src
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_STAGING.git master

